### PR TITLE
Implement astar_bag

### PR DESCRIPTION
**Pull request by samueltardieu**

### CODE REVIEW

**Comment by samueltardieu** [comment]
bors try

**Comment by samueltardieu** [comment]
bors try

**Comment by samueltardieu** [comment]
@ltratt If I were to keep this implementation, would you be ok with the attribution of those commits?

**Comment by ltratt** [comment]
I don't think you should attribute this to me: you've done all the hard work! My version was a quick 10 minute hack just to show what might be possible.

**Comment by ltratt** [comment]
[I like your version better FWIW.]

**Comment by ltratt** [comment]
Having finally gotten Rust nightly to build (it's needed for this PR), this works well for me -- thanks :) I prefer your return type `(Vec<Vec<N>>, C)` over what I proposed.

One possible optimisation: at the moment this PR will always insert neighbours into the binary tree, even if their estimated costs exceeds the min cost. Given that I imagine insertion is (occasionally) expensive, I wonder if it's worth trying to prune out such elements before insertion?

**Comment by samueltardieu** [comment]
You might want to benchmark that.

Btw, why would rust nightly be needed?

**Comment by ltratt** [comment]
You're right -- I could just have upgraded to 1.21. Doh. There was definitely some sort of warning on 1.20.

I'm not sure I have big enough graphs to get great quality benchmarking out of them. I could probably make an artificial benchmark if you'd like?

**Comment by samueltardieu** [comment]
In fact, this implementation (mine as well as yours) is incorrect. I've added some tests and you'll see that one is failing.

In the failing test, three solutions should be found. However, due to the fact that we do not explore nodes again if we have reached them with a shorter or equal path already, we do not find the other solutions.

I've tried the same test on your original implementation and it fails as well and only finds one solution. Did you test your code on an actual case btw?

**Comment by samueltardieu** [comment]
bors try

**Comment by ltratt** [comment]
That is very interesting! Yes, I'm using this code now (I'll probably open a PR on a project we're workng on that references this branch in the next few days). I hadn't noticed this problem, but I admit that I was sort-of taking the results from `astar_bag` on trust, and had focussed more on bugs in my code. Do you think it's easy to fix?

**Comment by samueltardieu** [comment]
I'm not sure. Moreover, let's assume that you have a maze looking like

```
......X....X....X....X....X....
A..X....X....X....X....X....X.B
......X....X....X....X....X....
```

and you want to go from `A` to `B` (obstacles are `X`). The idea here is that you have to go from the middle line to either the upper or the lower line, then back to the middle line, then again to either the upper or the lower line, and so on. You get very rapidly a large number of combinations (if you have _N_ times the choice to go to either the upper or the lower line, then you have 2<sup>_N_</sup> different paths).

As you see, it means that you have to go through numerous alternative paths. I am not sure this can be done easily while keeping a data structure similar to what is done right now. You would have to potentially discard parents for every node whose estimated cost is greater or equal than the currently esimated cost I think.

**Comment by ltratt** [comment]
Yes, I've been thinking a bit about this, and I think it also requires a slightly different approach. I'm not totally sure what that approach should be though :/

**Pull request closed without merging**
