### PR TITLE
Add (working) sketch of an "all_astar" function.

### PR DESCRIPTION
**Pull request by ltratt**
This PR is more of a request for comments than a "please merge me now!" PR.

In essence: I need to find *all* the shortest paths in a graph. The `astar` function (for example) has a wonderful API, but only gives me *a* shortest path. So I minimally hacked it so that it returns a `Vec` (maybe it should be a `HashSet` to make clear there's a lack of ordering? But that's probably overkill...) with all of the shortest paths. I'm not claiming this is the right API, or that this is the right way to go about modifying the internals, but might something like this be of interest?

### CODE REVIEW

**Comment by samueltardieu** [comment]
Wouldn't it be better, complexity-wise, to implement [Floyd-Warshall](https://en.wikipedia.org/wiki/Floyd–Warshall_algorithm) algorithm instead?

**Comment by ltratt** [comment]
I'm not an expert in this area (to say the least!), but my understanding of Floyd-Warshall is captured in this bit: "A single execution of the algorithm will find the lengths (summed weights) of the shortest paths between all pairs of vertices." AIUI, that will find paths for every pair of nodes in the graph. I just want to find the shortest paths from the start to the success node(s). Warning: I might be very wrong about this!

**Comment by samueltardieu** [comment]
You're right, but since you wrote earlier "I need to find all the shortest paths in a graph", that corresponds to finding the shortest paths between all pairs of vertices :-)

If you need to find all the shortest paths from a given starting vertex, then the full Dijkstra algorithm (which does not stop when a particular destination is found) might be the most efficient way to do this.

**Comment by ltratt** [comment]
You're quite right, what I wrote was ambiguous -- sorry!

In my case, I have a heuristic for the distance to a success node, so the A* algorithm seems more appropriate. The hack contained in this PR, in essence, doesn't stop at the first node found: every time a success node is found, the path is pushed to the vec `out`. So the output of `all_astar` is a vector of paths: if the vector is empty, no paths were found. From an API perspective, this seems reasonably nice, although I'm not claiming the way I hacked the `astar` function is particularly beautiful. I also made one optimisation: once *a* shortest path has been found, we can cull any paths whose cost would exceed that shortest path (which seems to help quite a bit in my examples).

**Comment by samueltardieu** [comment]
Since you're going to explore all vertices reachable from your source vertex anyway, I'm not sure the heuristic brings anything useful performance wise.

**Comment by ltratt** [comment]
My patch doesn't explore all reachable vertices: once we've found a shortest path, that provides a bounded cost that prevents vertices that exceed that cost ever being explored.

Another way of looking at this is that the current `astar` function non-deterministically returns a shortest path for a graph G: my function is morally equivalent to rerunning `astar` and collecting all the shortest paths found. `all_astar` won't explore any edge that `astar` doesn't explore in one of its (non-deterministic) runs.

**Comment by samueltardieu** [comment]
Ok, I've read it too quickly, I thought you were returning a collection of shortest paths from the source node to any other node. What you're doing is return all paths from source to success nodes that share the smallest cost, if I get it right this time.

I'll have a look later at it then.

bors try

**Comment by ltratt** [comment]
Yes, that's a good summary of the change!

**Comment by ltratt** [comment]
Hello Samuel, Any thoughts on this? --Laurie

**Comment by samueltardieu** [comment]
Yes. I've been sick for a few days so I haven't been productive, but I'm coming up with an alternate solution.

It's not finished (no test), but I've just pushed the `bag` branch. I absolutely hate repeating myself, so your solution with quasi identical code between `astar` and `aster_all` does not suit me. I've built an intermediate function, with an `early_stop` parameter, which is used both by `astar` and `astar_bag` (bag of solutions is a common term here).

**Comment by samueltardieu** [comment]
I've done the attribution, and I'll test the PR even if I won't merge it right away because it has no tests yet and I'm not sure it is entirely correct.

**Comment by samueltardieu** [comment]
Superseded by #44, let's continue the discussion there.

**Pull request closed without merging**
