### PR TITLE
Prioritize nodes using correct cost value in a*

### PR DESCRIPTION
**Pull request by ehsanul**
When prioritizing between equal estimated-cost nodes, seems it was incorrectly
using the parent node's cost so far. Instead, it's own cost so far should be
used.

Consider a simple graph:

    A ----> B
       \
        --> C

Where A is the start node, and B and C have equal estimated cost, but different
cost so far. The "cost" value would previously be 0 for both B and C in the smallest cost
holder, thus not ensuring that the lowest cost-so-far node is picked for
expansion first.

### CODE REVIEW

**Comment by ehsanul** [comment]
Ok after doing that change I then noticed the cost is duplicated, so I've cleaned that up too.

**Comment by samueltardieu** [comment]
Indeed that looks like a sensible change. I'll probably rename `payload_index` into `parent_index` later.

bors r+

**Comment by samueltardieu** [comment]
Would you be kind enough to squash your three commits and make the following changes?

- the use of the name `parent_index` instead of `payload_index`;
- the run of the latest `cargo fmt` (there was one slight [misformating](https://travis-ci.org/samueltardieu/pathfinding/jobs/401633502)).

Thanks in advance.

**Comment by ehsanul** [comment]
@samueltardieu Done. I've renamed the variable too, but I'd like to observe that `parent_index` may easily be misread as "index of my parent", which is not what you're going for clearly

**Comment by samueltardieu** [comment]
Indeed. What about `node_index`, or `index` without qualification?

**Comment by samueltardieu** [comment]
Thanks @ehsanul!

**Pull request merged**
