### PR TITLE
yen: Implement Yen's algorithm

### PR DESCRIPTION
**Pull request by dsp**
Yen's algorithm is a graph algorithm to find k-shortests paths. It is
useful to provide alternative paths besides the shortest path.
An explanation of the algorithm can be found here
https://en.wikipedia.org/wiki/Yen's_algorithm.

This commit implements a basic version of yen's algorithm based on the
linked wikipedia article with a binary min-heap to speed up the candidate
selection. A basic set of tests has been implemented. No benchmarking has
been performed so far. The current time complexity is O(KN^3), assuming the
Dijkstra implementation is O(N^2).

Please note that this pull request is meant to understand if the change is welcomed and
to start a discussion. I am sure there is plenty of work left here, but I would love to get an initial
look from the maintainers to see what needs changing.

### CODE REVIEW

**Comment by dsp** [comment]
Note that one of the items I want to discuss is my use of the `Path` struct. I personally prefer this and I think it's intuitive for users of the library, but it breaks with conventions from `dijkstra` and functions. So I am happy to change that if needed.

Another aspect is that unlike dijkstra I was not yet able to mark `successors` as `FnMut` but only `Fn` to avoid move semantics when creating the `filtered_successors` callback. This has implications for users as they cannot modify state. I feel as a first implementation it might be fine to have this limitation but it's something I am looking for feedback on.

**Comment by samueltardieu** [comment]
Hi @dsp. Your contribution looks really interesting.

Concerning your numbered bullets:

1. Indeed, a `Path` struct could be useful, but it would be better if we used it on other algorithms as well but that would require a major version change as this would break compatibility. I would prefer that we use `(Vec<N>, C)` until this is changed everywhere in a future major release.
2. We could provide a crate-visible `dijkstra_internal` which takes `successors` and `success` functions as `&mut FnMut`, so that they are not consumed.
3. I'm not sure this would be useful there. Other Yen implementations I know of don't allow this either.

Some additional remarks:

- There is an issue in your code: you store only hashes in your `visited` set; hashes are not unique and collisions might happen, you cannot rely on luck there. You have to insert the full path in the set (after cloning it) and looking it up this way as well. Hashes will be used internally to speed up the lookup, but a path comparison is required if hashes match. The `hash()` function is not required.
- Please do not use `#[inline]` unless you have measured execution times on several platforms and you can guarantee that the compiler is not clever enough to know what to do. In general, inlining a module-private function is not needed.
- In `make_cost()` function signature, `N` does not need to be `Hash` nor `Clone` (`Eq` is enough), and `C` does not need to be `Ord` nor `Copy` (`Zero` is enough), let's keep the type bounds to a minimum as it allows easier evolution later on. Also, there is no need to make a special case for an empty `nodes` as the loop will just not run.
- You do not need the `make_path()` function, you can use `let nodes: Vec<N> = root_path.iter().cloned().chain(spur_path).collect();` which will even be more efficient as `nodes` will allocate the right capacity from the start as `Chain` implements `TrustedLen`.
- The result needs not be wrapped in an `Option`. An empty vector means there is no path already.
- I prefer to have the tests in separate files, as it makes it easier to transform them into benchmarks.
- The comment on the latest test is wrong, maybe it should be something along the lines of "Test that we support loops".

If you are ok with this, I have a branch (`yen`) which does this on top of your work and that you can examine. Or, if you prefer, you can integrate the changes I made to `yen.rs` in your code, and force push this branch.

**Comment by samueltardieu** [comment]
(I opened PR #278 to get the CI to check those proposed changes)

**Comment by samueltardieu** [comment]
Also, in `sort_unstable()` might be more efficient than `sort()`.

**Comment by dsp** [comment]
Thank you for the thoughts on the pull request and the thorough review. I really appreciate you going as far as fixing them right away! All your proposed changes make sense to me.

I added two minor changes to the pull request to make `Path` private (and hence not exposed in docs) and fix the doctest import accordingly. I am happy with whatever works for you in terms of merging (your pull request, my pull request).

**Comment by dsp** [comment]
BTW as a further optimization that we can look into, if `dijkstra_internal` would return (node, cost)-vectors instead of node vectors and a cost, we could recalculate the path cost cheaper without having to traverse the nodes again.

**Comment by samueltardieu** [comment]
> BTW as a further optimization that we can look into, if `dijkstra_internal` would return (node, cost)-vector instead of node vectors and a cost, we could recalculate the path cost cheaper without having to traverse the nodes again.

We will be able to change it later if needed as this is purely internal.

**Comment by samueltardieu** [comment]
@dsp: pathfinding 2.1.3 has been released with these changes. Thanks.

**Pull request merged**
